### ISSUE TITLE
issue with XGBOOST preds

### ISSUE THREAD

**Issue by kevinVervier** [nunompmoniz/autoresampling#1]
Hi there,

When running ATOMIC(), I get an error, likely from this line:

` preds <- stats::predict(sysdata$metamodel.class, xgbTest)`

```
Error in xgb.Booster.handle(modelfile = object$raw) : 
  [13:05:19] ../../amalgamation/../src/objective/objective.cc:26: Unknown objective function: ``
Objective candidate: reg:squarederror
Objective candidate: reg:squaredlogerror
Objective candidate: reg:logistic
Objective candidate: binary:logistic
Objective candidate: binary:logitraw
Objective candidate: reg:linear
Objective candidate: count:poisson
Objective candidate: survival:cox
Objective candidate: reg:gamma
Objective candidate: reg:tweedie
Objective candidate: multi:softmax
Objective candidate: multi:softprob
Objective candidate: rank:pairwise
Objective candidate: rank:ndcg
Objective candidate: rank:map
Objective candidate: binary:hinge

Stack trace:
  [bt] (0) /shared/kvervier/venv/ml_venv/lib/R/library/xgboost/libs/xgboost.so(+0x7d8bf) [0x7f2887fac8bf]
  [bt] (1) /shared/kvervier/venv/ml_venv/lib/R/library/xgboost/libs/xgboost.so(xgboost::ObjFunction::Create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, xgboost::GenericParameter 
```

**Comment by nunompmoniz** [comment]
Hi Kevin!

Could you provide some code to better understand where the problem could be coming from, along with the sessionInfo() data?

Thanks!

**Comment by kevinVervier** [comment]
sessionInfo() output:

R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS/LAPACK: /shared/kvervier/venv/ml_venv/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] autoresampling_0.1.0   cowplot_1.0.0          MachineShop_2.4.0     
 [4] doParallel_1.0.16      iterators_1.0.13       foreach_1.5.1         
 [7] dplyr_0.8.5            xgboost_1.4.1.1        tree.interpreter_0.1.1
[10] Rtsne_0.15             Spectrum_1.1           RColorBrewer_1.1-2    
[13] randomForest_4.6-14    iRF_2.0.0              AUC_0.3.0             
[16] ALDEx2_1.18.0          ggpubr_0.2.5           magrittr_2.0.1        
[19] ggplot2_3.3.2          Maaslin2_0.99.12       phyloseq_1.30.0       
[22] zCompositions_1.3.4    truncnorm_1.0-8        NADA_1.6-1.1          
[25] survival_3.2-3         MASS_7.3-51.5          vegan_2.5-6           
[28] lattice_0.20-40        permute_0.9-5          knitr_1.22            

loaded via a namespace (and not attached):
  [1] backports_1.1.5             plyr_1.8.6                 
  [3] igraph_1.2.6                sp_1.4-5                   
  [5] splines_3.6.1               entropy_1.2.1              
  [7] gmp_0.6-0                   BiocParallel_1.20.0        
  [9] listenv_0.8.0               gstat_2.0-7                
 [11] GenomeInfoDb_1.22.0         TH.data_1.0-10             
 [13] lpsymphony_1.14.0           digest_0.6.18              
 [15] MLmetrics_1.1.1             cluster_2.1.0              
 [17] Metrics_0.1.4               remotes_2.2.0              
 [19] recipes_0.1.5               globals_0.12.5             
 [21] Biostrings_2.54.0           gower_0.2.0                
 [23] matrixStats_0.56.0          xts_0.12.1                 
 [25] sandwich_2.5-1              rsample_0.0.7              
 [27] prettyunits_1.1.1           strucchange_1.5-1          
 [29] dials_0.0.8                 colorspace_1.4-1           
 [31] xfun_0.6                    callr_3.5.1                
 [33] crayon_1.3.4                RCurl_1.98-1.1             
 [35] jsonlite_1.7.2              libcoin_1.0-4              
 [37] zoo_1.8-9                   ape_5.3                    
 [39] glue_1.3.1                  gtable_0.3.0               
 [41] ipred_0.9-8                 zlibbioc_1.32.0            
 [43] XVector_0.26.0              DelayedArray_0.12.0        
 [45] pkgbuild_1.2.0              kernlab_0.9-27             
 [47] Rhdf5lib_1.8.0              RcppZiggurat_0.1.5         
 [49] BiocGenerics_0.32.0         abind_1.4-5                
 [51] scales_1.1.0                mvtnorm_1.1-0              
 [53] infotheo_1.2.0              Rcpp_1.0.6                 
 [55] progress_1.2.2              proxy_0.4-25               
 [57] intervals_0.15.2            stats4_3.6.1               
 [59] lava_1.6.5                  prodlim_2018.04.18         
 [61] getopt_1.20.3               FNN_1.1.3                  
 [63] modeltools_0.2-22           ClusterR_1.2.2             
 [65] reshape_0.8.8               pkgconfig_2.0.3            
 [67] nnet_7.3-13                 tidyselect_1.0.0           
 [69] rlang_0.4.10                DiceDesign_1.8-1           
 [71] reshape2_1.4.3              munsell_0.5.0              
 [73] tools_3.6.1                 cli_2.3.1                  
 [75] moments_0.14                party_1.3-3                
 [77] generics_0.0.2              ade4_1.7-15                
 [79] biomformat_1.14.0           stringr_1.4.0              
 [81] processx_3.4.5              purrr_0.3.3                
 [83] coin_1.3-0                  future_1.18.0              
 [85] nlme_3.1-145                compiler_3.6.1             
 [87] curl_4.3                    e1071_1.7-6                
 [89] ggsignif_0.6.0              UBL_0.0.7                  
 [91] spacetime_1.2-4             tibble_2.1.3               
 [93] stringi_1.4.3               ps_1.6.0                   
 [95] Matrix_1.2-18               multtest_2.42.0            
 [97] vctrs_0.3.2                 pillar_1.4.3               
 [99] lifecycle_0.2.0             furrr_0.1.0                
[101] optparse_1.6.4              data.table_1.14.0          
[103] bitops_1.0-6                GenomicRanges_1.38.0       
[105] R6_2.4.1                    IRanges_2.20.0             
[107] codetools_0.2-16            polspline_1.1.14           
[109] gtools_3.8.2                assertthat_0.2.1           
[111] MBA_0.0-9                   rhdf5_2.30.0               
[113] SummarizedExperiment_1.16.0 rprojroot_1.3-2            
[115] withr_2.4.1                 multcomp_1.4-10            
[117] S4Vectors_0.24.0            GenomeInfoDbData_1.2.2     
[119] diptest_0.75-7              mgcv_1.8-31                
[121] hms_0.5.3                   grid_3.6.1                 
[123] rpart_4.1-15                timeDate_3043.102          
[125] tidyr_1.0.2                 class_7.3-16               
[127] Rfast_1.9.9                 automap_1.0-14             
[129] minerva_1.5.8               Biobase_2.46.0             
[131] lubridate_1.7.4             ECoL_0.3.0

**Comment by kevinVervier** [comment]
Some extra code (essentially using your tutorial code with my own data.frame with ~ 1,000 features and ~100 samples).
the numCores argument is what I implemented to allow parallel computing during metafeature creation

`set.seed(42)
df = data.frame(Y,X)
ind <- sample(1:nrow(df), 0.7*nrow(df)) 
train <- df[ind,]
test <- df[-ind,]
atomic.m <- ATOMIC(Y ~ .,train,metric = 'AUC',numCores = 16) # Build the ATOMIC solution`

**Comment by nunompmoniz** [comment]
Ran it on this side, and it seems to be working well. Does it run with metric='F1'?
The AUC metric is still not implemented although results are already available - it uses the metamodel optimised to predict the F1 Score. I'll create an assertion for this, to prevent it in the future.

**Comment by kevinVervier** [comment]
I tried to run the example from the blog with PimaIndiansDiabetes, and still get the same issue (using F1).

**Comment by kevinVervier** [comment]
It looks like the issue was caused by a conflict with another R package I loaded in the same environment prior to autoresampling (maybe xgboost).
All working now.

**Comment by nunompmoniz** [comment]
Glad that it's working. Any chance you know the package that was causing the conflict? In case someone else finds the same issue.

**Comment by kevinVervier** [comment]
Hard to tell. I suspect the MachineShop package (https://github.com/brian-j-smith/MachineShop) might overwrite some functions.
